/* eslint-disable */

/**
 * Generated by @openapi-codegen
 *
 * @version 2022-07-29 08:18:09UTC
 */
export type TravelRecord = {
  title: string
  /**
   * @format date
   */
  start: string
  /**
   * @format date
   */
  end: string
}

export type TravelDataRequestBody = {
  userName: string
  /**
   * @format int64
   */
  travelRecordId: number
}

export type PostTravelReturn = {
  status: string
  message: string
  /**
   * @format int64
   */
  travelId?: number
}

export type DeleteTravelReturn = {
  status: string
  message: string
}

export type TravelData = {
  status: string
  message: string
  /**
   * @format int64
   */
  travelId?: number
  /**
   * @format int64
   */
  userId?: number
  /**
   * @format int64
   */
  travelRecordId?: number
}

export type TravelRecordRequestBody = {
  userName: string
  title?: string
  /**
   * @format int64
   */
  startDate?: number
  /**
   * @format int64
   */
  endDate?: number
}

export type CreateTravelRecordReturn = {
  status: string
  message: string
  /**
   * @format int64
   */
  travelRecordId?: number
}

export type DeleteTravelRecordReturn = {
  status: string
  message: string
}

export type CreateUserReturn = {
  status: string
  message: string
  /**
   * @format int64
   */
  userId?: number
}

export type DeleteUserReturn = {
  status: string
  message: string
}

export type PhotoRequestBody = {
  description?: string
  /**
   * @format int64
   */
  travelRecordId: number
  fileName: string
  filePath: string
  isFavorite?: string
}

export type PostPhotoReturn = {
  status: string
  message: string
  /**
   * @format int64
   */
  photoId?: number
}

export type UserData = {
  status: string
  message: string
  /**
   * @format int64
   */
  userId?: number
  userName?: string
}
